### ISSUE TITLE
Question: Word filters, as seen in zendframework/zend-filter?

### ISSUE THREAD

**Issue by localheinz** [particle-php/Filter#33]
Wondering, is there anyone else out there interested in word filters, as you may have seen them in [`zendframework/zend-filter`](https://github.com/zendframework/zend-filter/tree/master/test/Word)?

/cc @rcatlin @kayladnls

**Comment by rick-nu** [comment]
@localheinz I've been thinking about this, but the problem here is is that you most likely want to use those filters for array keys. For example, from database keys to api keys: `active_till` -> `activeTill`, `user_permissions` -> `UserPermissions`, ect. The filter is in essence not build to filter keys, but values. Maybe we could think of a way to make it possible to filter the keys as well, but I have the feeling that should be in another particle then.

**Comment by rick-nu** [comment]
Closing this question, feel free to re-open if there are some follow up questions.
