### ISSUE TITLE
Removing keys from validated array

### ISSUE THREAD

**Issue by jhuet** [particle-php/Filter#42]
I'm discovering your 2 libraries and i gotta say that it's some nice pieces of work :)

I found that it's possible to create keys into the validated array thanks to the `callback` method. I think it would also make sense to allow the removal of keys. For example it often happens that data sent from the form contains things that need to be filtered out like CSRF tokens. Why not handling this in the filter itself ?

**Comment by rick-nu** [comment]
Great feature request, I'll definitely look into this :) I hope any time soon, can't make promises though. Thank you :smile:

**Comment by jhuet** [comment]
Hey there, if you want i could try an implementation of this. I'd gladly take a few inputs on where to start though :)

**Comment by rick-nu** [comment]
@jhuet it is pretty hard to explain as it hits pretty much every layer of the library, but I've made a first draft now in #43. Still need to beautify it, but it seems to doing what we want :)

**Comment by rick-nu** [comment]
Feature completed, and released in https://github.com/particle-php/Filter/releases/tag/v1.3.0 :D

**Comment by jhuet** [comment]
Awesome ! Sorry i didn't have time to check it out, but thank you so much for doing it !

**Comment by jhuet** [comment]
Before opening another issue, i wanted your opinion on a different way to see this feature. Do you think that saying : keep only these keys, instead of : remove these keys would be useful ? I feel like it'd be easier and also safer to limit the content of an array by saying i want to keep only these keys.

What do you think ?

**Comment by rick-nu** [comment]
@jhuet I've thought about this, but I think this is out of scope off the filter. If you want to be sure what data and keys are valid, I would suggest that you use Particle Validator for that. Not only does that validate the contents, but it also has the function `$result = $validator->validate(); $result->getValues()` which will only return the values that are validated.

The problem is, that this request is conflicting with `$filter->all()`, which will loop over all values of the array. It's either keep that, or allow to only result targeted keys. I think it will be 'hacky' to make work arounds for it. But feel free to try :wink:

**Comment by rick-nu** [comment]
So coming back to this, because there is a simple solution. A whitelist. I will create a new feature ticket for this.

### Example

``` php
$f = new Filter;
$f->whiteList(['first_name']);

$result = $f->filter([
  'first_name' => 'john',
  'spam' => 'spam'
]);
/**
 * array(1) {
 *     ["first_namet"]=> string(4) "john"
 * } 
 */
```
